---
title: "DC Analysis"
output:
  pdf_document: default
  html_notebook: default
editor_options: 
  markdown: 
    wrap: 72
---
## Libraries and Data
```{r Libraries, warning=FALSE}
#load libraries
library(ipumsr)
library(dplyr)
library(rdrobust)
library(ggplot2)
library(rddtools)
library(gridExtra)
```

```{r Data}
#load acs data
acsddi <- read_ipums_ddi("usa_00007.xml")
acs <- read_ipums_micro(acsddi)
```

## Data Cleaning
```{r subgroups and relevant variables}
#make subgroups
parents <- subset(acs, acs$YNGCH <= 18)

#turn educ into years in school
parents$MYEDUC <- NA
parents$MYEDUC[parents$EDUC == 0] <- 0
parents$MYEDUC[parents$EDUC == 01] <- 3
parents$MYEDUC[parents$EDUC == 02] <- 8
parents$MYEDUC[parents$EDUC == 03] <- 10
parents$MYEDUC[parents$EDUC == 04] <- 11
parents$MYEDUC[parents$EDUC == 05] <- 12
parents$MYEDUC[parents$EDUC == 06] <- 13
parents$MYEDUC[parents$EDUC == 07] <- 14
parents$MYEDUC[parents$EDUC == 08] <- 15
parents$MYEDUC[parents$EDUC == 09] <- 16
parents$MYEDUC[parents$EDUC == 10] <- 17
parents$MYEDUC[parents$EDUC == 11] <- 18
parents$MYEDUC[parents$EDUCD == 110] <- 18 #5+ years of college
parents$MYEDUC[parents$EDUCD == 111] <- 19 #6 years of college
parents$MYEDUC[parents$EDUCD == 112] <- 20 #7 years of college
parents$MYEDUC[parents$EDUCD == 113] <- 21 #8+ years of college
parents$MYEDUC[parents$EDUCD == 114] <- 19 #Master's degree (assuming 2 years)
parents$MYEDUC[parents$EDUCD == 115] <- 20 #Professional degree beyond a bachelor's degree (assuming 3 years)
parents$MYEDUC[parents$EDUCD == 116] <- 24 #doctorate degree (assuming 4 years of undergrad + 2 years masters + 6 years PhD)

#make birthplace a binary variable to code immigrants vs. nonimmigrants
parents$immigrant <- 0
parents$immigrant[parents$BPL >= 100] <- 1

#make binary married/not married variable
parents$married <- if_else(parents$MARST == 1, 1, 0)

#make binary race variables
parents$white <- if_else(parents$RACE == 1, 1, 0)
parents$black <- if_else(parents$RACE == 2, 1, 0)
parents$asian <- if_else(parents$RACE == 4 | parents$RACE == 5 | parents$RACE == 6, 1, 0)
parents$otherormixedrace <- if_else(parents$RACE == 7 | parents$RACE == 8 | parents$RACE == 9, 1, 0)

#separate moms
moms <- subset(parents, parents$SEX == 2)

#binary variable for bachelor's degree: 101 = bachelor’s degree, 081 = associate’s degree, 114 = master’s degree, 115 = professional degree beyond bachelors, 116 = doctoral degree

moms$bachelor <- if_else(moms$EDUCD == 101 | moms$EDUCD == 114 | moms$EDUCD == 115 | moms$EDUCD == 116, 1, 0)
moms$associates_or_up <- if_else(moms$EDUCD == 101 | moms$EDUCD == 81 | moms$EDUCD == 114 | moms$EDUCD == 115 | moms$EDUCD == 116, 1, 0)
moms$postgrad <- if_else(moms$EDUCD == 114 | moms$EDUCD == 115 | moms$EDUCD == 116, 1, 0)

#separate moms by state
dcmoms <- subset(moms, moms$STATEICP == 98)
floridamoms <- subset(moms, moms$STATEICP == 43)

#use dcmoms and floridamoms as the github code!
```


## Educational Attainment

```{r DC 5 years educ}
#dc rdd 5 years after implementation, educational attainment

#create initial subset
dc5yrs_educ <- subset(dcmoms, dcmoms$YEAR == 2014)

#create data table for regression
dc5yrs_reg <- rdd_data(y = dc5yrs_educ$MYEDUC, x = dc5yrs_educ$YNGCH, cutpoint = 10)

#find optimal bandwidth
bw_ik <- rdd_bw_ik(dc5yrs_reg)

#run regression based on optimal bandwidth
(reg_nonpara5 <- rdd_reg_np(rdd_object=dc5yrs_reg, bw=bw_ik))

#adjust subset based on optimal bandwidth
dc5yrs_educ <- subset(dc5yrs_educ, dc5yrs_educ$YNGCH >= 4 & dc5yrs_educ$YNGCH <= 16)
  
#plot regression discontinuity graph
dc_educ_plot5 <- rdplot(dc5yrs_educ$MYEDUC, x = dc5yrs_educ$YNGCH, c = 10, p = 1, masspoints = "off", col.dots = "black", col.lines = "black", title = "2014", x.label = "Age of Youngest Child", y.label = "Years in School")

#bandwidth sensitivity test
bw_test <- plotSensi(reg_nonpara5, from=2, to=18, by=1, plot = FALSE)
dc_educ_bw5 <- ggplot(bw_test, aes(x=bw, y=LATE)) + 
  geom_line() +
  geom_ribbon(aes(ymin = CI_low, ymax = CI_high),alpha=0.2) +
  geom_point(x = 6.691201, y = 0.8835) +
  ggtitle("2014") +
  xlab("Bandwidth") +
  ylab("Treatment effect") +
  geom_hline(yintercept = 0, alpha = 0.5)
```

```{r DC 4 years educ}
#dc rdd 4 years after implementation, educational attainment

#create initial subset
dc4yrs_educ <- subset(dcmoms, dcmoms$YEAR == 2013)

#create data table for regression
dc4yrs_reg <- rdd_data(y = dc4yrs_educ$MYEDUC, x = dc4yrs_educ$YNGCH, cutpoint = 9)

#find optimal bandwidth
bw_ik <- rdd_bw_ik(dc4yrs_reg)

#run regression based on optimal bandwidth
(reg_nonpara4 <- rdd_reg_np(rdd_object=dc4yrs_reg, bw=bw_ik))

#adjust subset based on optimal bandwidth
dc4yrs_educ <- subset(dc4yrs_educ, dc4yrs_educ$YNGCH >= 2 & dc4yrs_educ$YNGCH <= 16)
  
#plot regression discontinuity graph
dc_educ_plot4 <-rdplot(dc4yrs_educ$MYEDUC, x = dc4yrs_educ$YNGCH, c = 9, p = 1, masspoints = "off", col.dots = "black", col.lines = "black", title = "2013", x.label = "Age of Youngest Child", y.label = "Years in School")

#bandwidth sensitivity test
bw_test <- plotSensi(reg_nonpara4, from=2, to=18, by=1)
dc_educ_bw4 <- ggplot(bw_test, aes(x=bw, y=LATE)) + 
  geom_line() +
  geom_ribbon(aes(ymin = CI_low, ymax = CI_high),alpha=0.2) +
  geom_point(x = 7.749977, y = -1.43739) +
  ggtitle("2013") +
  xlab("Bandwidth") +
  ylab("Treatment effect") +
  geom_hline(yintercept = 0, alpha = 0.5)
```


```{r DC 3 years educ}
#dc rdd 3 years after implementation, educational attainment

#create initial subset
dc3yrs_educ <- subset(dcmoms, dcmoms$YEAR == 2012)

#create data table for regression
dc3yrs_reg <- rdd_data(y = dc3yrs_educ$MYEDUC, x = dc3yrs_educ$YNGCH, cutpoint = 8, covar = dc3yrs_educ$AGE)

#find optimal bandwidth
bw_ik <- rdd_bw_ik(dc3yrs_reg)

#run regression based on optimal bandwidth
(reg_nonpara3 <- rdd_reg_np(rdd_object=dc3yrs_reg, bw=bw_ik))

#don't need to adjust subset because bandwidth covers the entire sample
  
#plot regression discontinuity graph
dc_educ_plot3 <- rdplot(dc3yrs_educ$MYEDUC, x = dc3yrs_educ$YNGCH, c = 8, p = 1, masspoints = "off", col.dots = "black", col.lines = "black", title = "2012", x.label = "Age of Youngest Child", y.label = "Years in School")

#bandwidth sensitivity test
bw_test <- plotSensi(reg_nonpara3, from=2, to=18, by=1)
dc_educ_bw3 <- ggplot(bw_test, aes(x=bw, y=LATE)) + 
  geom_line() +
  geom_ribbon(aes(ymin = CI_low, ymax = CI_high),alpha=0.2) +
  geom_point(x =  10.01765, y = 0.75440) +
  ggtitle("2012") +
  xlab("Bandwidth") +
  ylab("Treatment effect") +
  geom_hline(yintercept = 0, alpha = 0.5)
```
this positive effect might come from the outliers on the left side of the cutoff point, the few points that are very low

```{r DC 2 years educ}
#DC 2 years after implementation, educational attainment

#create initial subset
dc2yrs_educ <- subset(dcmoms, dcmoms$YEAR == 2011)

#create data table for regression
dc2yrs_reg <- rdd_data(y = dc2yrs_educ$MYEDUC, x = dc2yrs_educ$YNGCH, cutpoint = 7)

#find optimal bandwidth
bw_ik <- rdd_bw_ik(dc2yrs_reg)

#run regression based on optimal bandwidth
(reg_nonpara2 <- rdd_reg_np(rdd_object=dc2yrs_reg, bw=bw_ik))

#adjust subset based on optimal bandwidth
dc2yrs_educ <- subset(dc2yrs_educ, dc2yrs_educ$YNGCH >= 1 & dc2yrs_educ$YNGCH <= 13)

  
#plot regression discontinuity graph
dc_educ_plot2 <-rdplot(dc2yrs_educ$MYEDUC, x = dc2yrs_educ$YNGCH, c = 7, p = 1, masspoints = "off", col.dots = "black", col.lines = "black", title = "2011", x.label = "Age of Youngest Child", y.label = "Years in School")

#bandwidth sensitivity test
bw_test <- plotSensi(reg_nonpara2, from=2, to=18, by=1)
dc_educ_bw2 <- ggplot(bw_test, aes(x=bw, y=LATE)) + 
  geom_line() +
  geom_ribbon(aes(ymin = CI_low, ymax = CI_high),alpha=0.2) +
  geom_point(x = 6.665755, y = -1.43141) +
  ggtitle("2011") +
  xlab("Bandwidth") +
  ylab("Treatment effect") +
  geom_hline(yintercept = 0, alpha = 0.5)
```


```{r grid plots educ}
#make grid plots

educ_dc_grid <- grid.arrange(grobs = list(dc_educ_plot2$rdplot, dc_educ_plot3$rdplot, dc_educ_plot4$rdplot, dc_educ_plot5$rdplot), ncol = 2, nrow = 2, top = "Educational Attainment of Mothers in Washington, DC")

educ_dc_bw_grid <- grid.arrange(grobs = list(dc_educ_bw2, dc_educ_bw3, dc_educ_bw4, dc_educ_bw5), ncol = 2, nrow = 2, top = "Bandwidth Sensitivity Tests - Educational Attainment of Mothers in Washington, DC")

```


## Bachelor's Degree

```{r DC 2 years bachelor's}
#DC 2 years after implementation, bachelor's degree

#create initial subset
dc2yrs <- subset(dcmoms, dcmoms$YEAR == 2011)

#create data table for regression
dc2yrs_reg <- rdd_data(y = dc2yrs$bachelor, x = dc2yrs$YNGCH, cutpoint = 7)

#find optimal bandwidth
bw_ik <- rdd_bw_ik(dc2yrs_reg)

#run regression based on optimal bandwidth
(reg_nonpara2 <- rdd_reg_np(rdd_object=dc2yrs_reg, bw=bw_ik))

#no subset adjustment needed because optimal bandwidth covers all observations
dc2yrs <- subset(dc2yrs, dc2yrs$YNGCH >= 0 & dc2yrs$YNGCH <= 14)
  
#plot regression discontinuity graph
dc_bachelor_plot2 <- rdplot(y = dc2yrs$bachelor, x = dc2yrs$YNGCH, c = 7, p = 1, masspoints = "off", col.dots = "black", col.lines = "black", title = "2011", x.label = "Age of Youngest Child", y.label = "% Bachelor")

#bandwidth sensitivity test
bw_test <- plotSensi(reg_nonpara2, from=2, to=18, by=1)
dc_bachelor_bw2 <- ggplot(bw_test, aes(x=bw, y=LATE)) + 
  geom_line() +
  geom_ribbon(aes(ymin = CI_low, ymax = CI_high),alpha=0.2) +
  geom_point(x = 7.335013, y = -0.15399) +
  ggtitle("2011") +
  xlab("Bandwidth") +
  ylab("Treatment effect") +
  geom_hline(yintercept = 0, alpha = 0.5)
```

```{r DC 3 years bachelors}
#DC 3 years after implementation, bachelor's degree

#create initial subset
dc3yrs <- subset(dcmoms, dcmoms$YEAR == 2012)

#create data table for regression
dc3yrs_reg <- rdd_data(y = dc3yrs$bachelor, x = dc3yrs$YNGCH, cutpoint = 8, covar = dc3yrs$AGE)

#find optimal bandwidth
bw_ik <- rdd_bw_ik(dc3yrs_reg)

#run regression based on optimal bandwidth
(reg_nonpara3 <- rdd_reg_np(rdd_object=dc3yrs_reg, bw=bw_ik))

#no subset adjustment needed because optimal bandwidth covers all observations
  
#plot regression discontinuity graph
dc_bachelor_plot3 <- rdplot(y = dc3yrs$bachelor, x = dc3yrs$YNGCH, c = 8, p = 1, masspoints = "off", col.dots = "black", col.lines = "black", title = "2012", x.label = "Age of Youngest Child", y.label = "% Bachelor")

#bandwidth sensitivity test
bw_test <- plotSensi(reg_nonpara3, from=2, to=18, by=1)
dc_bachelor_bw3 <- ggplot(bw_test, aes(x=bw, y=LATE)) + 
  geom_line() +
  geom_ribbon(aes(ymin = CI_low, ymax = CI_high),alpha=0.2) +
  geom_point(x = 10.1113, y = 0.052683) +
  ggtitle("2012") +
  xlab("Bandwidth") +
  ylab("Treatment effect") +
  geom_hline(yintercept = 0, alpha = 0.5)
```

```{r DC 4 years bachelors}
#DC 4 years after implementation, bachelor's degree

#create initial subset
dc4yrs <- subset(dcmoms, dcmoms$YEAR == 2013)

#create data table for regression
dc4yrs_reg <- rdd_data(y = dc4yrs$bachelor, x = dc4yrs$YNGCH, cutpoint = 9, covar = dc4yrs$AGE)

#find optimal bandwidth
bw_ik <- rdd_bw_ik(dc4yrs_reg)

#run regression based on optimal bandwidth
(reg_nonpara4 <- rdd_reg_np(rdd_object=dc4yrs_reg, bw=bw_ik))

#no subset adjustment needed because optimal bandwidth covers all observations
  
#plot regression discontinuity graph
dc_bachelor_plot4 <- rdplot(y = dc4yrs$bachelor, x = dc4yrs$YNGCH, c = 9, p = 1, masspoints = "off", col.dots = "black", col.lines = "black", title = "2013", x.label = "Age of Youngest Child", y.label = "% Bachelor")

#bandwidth sensitivity test
bw_test <- plotSensi(reg_nonpara4, from=2, to=18, by=1)
dc_bachelor_bw4 <- ggplot(bw_test, aes(x=bw, y=LATE)) + 
  geom_line() +
  geom_ribbon(aes(ymin = CI_low, ymax = CI_high),alpha=0.2) +
  geom_point(x = 9.118557, y = -0.042280) +
  ggtitle("2013") +
  xlab("Bandwidth") +
  ylab("Treatment effect") +
  geom_hline(yintercept = 0, alpha = 0.5)
```

```{r DC 5 years bachelors}
#DC 5 years after implementation, bachelor's degree

#create initial subset
dc5yrs <- subset(dcmoms, dcmoms$YEAR == 2014)

#create data table for regression
dc5yrs_reg <- rdd_data(y = dc5yrs$bachelor, x = dc5yrs$YNGCH, cutpoint = 10)

#find optimal bandwidth
bw_ik <- rdd_bw_ik(dc5yrs_reg)

#run regression based on optimal bandwidth
(reg_nonpara5 <- rdd_reg_np(rdd_object=dc5yrs_reg, bw=bw_ik))

#no subset adjustment needed because optimal bandwidth covers all observations
dc5yrs <- subset(dc5yrs, dc5yrs$YNGCH >= 2 & dc5yrs$YNGCH <= 16)
  
#plot regression discontinuity graph
dc_bachelor_plot5 <- rdplot(y = dc5yrs$bachelor, x = dc5yrs$YNGCH, c = 10, p = 1, col.dots = "black", col.lines = "black", title = "2014", x.label = "Age of Youngest Child", y.label = "% Bachelor")

#bandwidth sensitivity test
bw_test <- plotSensi(reg_nonpara5, from=2, to=18, by=1)
dc_bachelor_bw5 <- ggplot(bw_test, aes(x=bw, y=LATE)) + 
  geom_line() +
  geom_ribbon(aes(ymin = CI_low, ymax = CI_high),alpha=0.2) +
  geom_point(x = 8.178698, y = 0.16356) +
  ggtitle("2014") +
  xlab("Bandwidth") +
  ylab("Treatment effect") +
  geom_hline(yintercept = 0, alpha = 0.5)
```

```{r grid plots bachelor}
#make grid plots

bachelor_dc_grid <- grid.arrange(grobs = list(dc_bachelor_plot2$rdplot, dc_bachelor_plot3$rdplot, dc_bachelor_plot4$rdplot, dc_bachelor_plot5$rdplot), ncol = 2, nrow = 2, top = "Rate of Bachelor's Degrees for Mothers in Washington, DC")

bachelor_dc_bw_grid <- grid.arrange(grobs = list(dc_bachelor_bw2, dc_bachelor_bw3, dc_bachelor_bw4, dc_bachelor_bw5), ncol = 2, nrow = 2, top = "Bandwidth Sensitivity Tests - Rates of Bachelor's Degrees for Mothers in Washington, DC")
```


## Any College Degree

```{r DC 2 years any degree}
#DC 2 years after implementation, any degree

#create initial subset
dc2yrs <- subset(dcmoms, dcmoms$YEAR == 2011)

#create data table for regression
dc2yrs_reg <- rdd_data(y = dc2yrs$associates_or_up, x = dc2yrs$YNGCH, cutpoint = 7)

#find optimal bandwidth
bw_ik <- rdd_bw_ik(dc2yrs_reg)

#run regression based on optimal bandwidth
(reg_nonpara2 <- rdd_reg_np(rdd_object=dc2yrs_reg, bw=bw_ik))

#no subset adjustment needed because optimal bandwidth covers all observations
dc2yrs <- subset(dc2yrs, dc2yrs$YNGCH <= 16)
  
#plot regression discontinuity graph
dc_all_plot2 <- rdplot(y = dc2yrs$associates_or_up, x = dc2yrs$YNGCH, c = 7, p = 1, masspoints = "off", col.dots = "black", col.lines = "black", title = "2011", x.label = "Age of Youngest Child", y.label = "% Any College Degree")

#bandwidth sensitivity test
bw_test <- plotSensi(reg_nonpara2, from=2, to=18, by=1)
dc_all_bw2 <- ggplot(bw_test, aes(x=bw, y=LATE)) + 
  geom_line() +
  geom_ribbon(aes(ymin = CI_low, ymax = CI_high),alpha=0.2) +
  geom_point(x = 7.423477, y = -0.095095) +
  ggtitle("2011") +
  xlab("Bandwidth") +
  ylab("Treatment effect") +
  geom_hline(yintercept = 0, alpha = 0.5)
```

```{r DC 3 years any degree}
#DC 3 years after implementation, any degree

#create initial subset
dc3yrs <- subset(dcmoms, dcmoms$YEAR == 2012)

#create data table for regression
dc3yrs_reg <- rdd_data(y = dc3yrs$associates_or_up, x = dc3yrs$YNGCH, cutpoint = 8)

#find optimal bandwidth
bw_ik <- rdd_bw_ik(dc3yrs_reg)

#run regression based on optimal bandwidth
(reg_nonpara3 <- rdd_reg_np(rdd_object=dc3yrs_reg, bw=bw_ik))

#adjust subset based on optimal bandwidth
dc3yrs <- subset(dc3yrs, dc3yrs$YNGCH <= 16)
  
#plot regression discontinuity graph
dc_all_plot3 <- rdplot(y = dc3yrs$associates_or_up, x = dc3yrs$YNGCH, c = 8, p = 1, masspoints = "off", col.dots = "black", col.lines = "black", title = "2012", x.label = "Age of Youngest Child", y.label = "% Any College Degree")

#bandwidth sensitivity test
bw_test <- plotSensi(reg_nonpara3, from=2, to=18, by=1)
dc_all_bw3 <- ggplot(bw_test, aes(x=bw, y=LATE)) + 
  geom_line() +
  geom_ribbon(aes(ymin = CI_low, ymax = CI_high),alpha=0.2) +
  geom_point(x = 15.598, y = 0.101174) +
  ggtitle("2012") +
  xlab("Bandwidth") +
  ylab("Treatment effect") +
  geom_hline(yintercept = 0, alpha = 0.5)
```

```{r DC 4 years any degree}
#DC 4 years after implementation, any degree

#create initial subset
dc4yrs <- subset(dcmoms, dcmoms$YEAR == 2013)

#create data table for regression
dc4yrs_reg <- rdd_data(y = dc4yrs$associates_or_up, x = dc4yrs$YNGCH, cutpoint = 9)

#find optimal bandwidth
bw_ik <- rdd_bw_ik(dc4yrs_reg)

#run regression based on optimal bandwidth
(reg_nonpara4 <- rdd_reg_np(rdd_object=dc4yrs_reg, bw=bw_ik))

#no subset adjustment needed because optimal bandwidth covers all observations
  
#plot regression discontinuity graph
dc_all_plot4 <- rdplot(y = dc4yrs$associates_or_up, x = dc4yrs$YNGCH, c = 9, p = 1, masspoints = "off", col.dots = "black", col.lines = "black", title = "2013", x.label = "Age of Youngest Child", y.label = "% Any College Degree")

#bandwidth sensitivity test
bw_test <- plotSensi(reg_nonpara4, from=2, to=18, by=1)
dc_all_bw4 <- ggplot(bw_test, aes(x=bw, y=LATE)) + 
  geom_line() +
  geom_ribbon(aes(ymin = CI_low, ymax = CI_high),alpha=0.2) +
  geom_point(x = 8.682466, y = -0.12705) +
  ggtitle("2013") +
  xlab("Bandwidth") +
  ylab("Treatment effect") +
  geom_hline(yintercept = 0, alpha = 0.5)
```

```{r DC 5 years any degree}
#DC 5 years after implementation, any degree

#create initial subset
dc5yrs <- subset(dcmoms, dcmoms$YEAR == 2014)

#create data table for regression
dc5yrs_reg <- rdd_data(y = dc5yrs$associates_or_up, x = dc5yrs$YNGCH, cutpoint = 10)

#find optimal bandwidth
bw_ik <- rdd_bw_ik(dc5yrs_reg)

#run regression based on optimal bandwidth
(reg_nonpara5 <- rdd_reg_np(rdd_object=dc5yrs_reg, bw=bw_ik))

#no subset adjustment needed because optimal bandwidth covers all observations
dc5yrs <- subset(dc5yrs, dc5yrs$YNGCH >= 3 & dc5yrs$YNGCH <= 15)

#plot regression discontinuity graph
dc_all_plot5 <- rdplot(y = dc5yrs$associates_or_up, x = dc5yrs$YNGCH, c = 10, p = 1, col.dots = "black", col.lines = "black", title = "2014", x.label = "Age of Youngest Child", y.label = "% Any College Degree")

#bandwidth sensitivity test
bw_test <- plotSensi(reg_nonpara5, from=2, to=18, by=1)
dc_all_bw5 <- ggplot(bw_test, aes(x=bw, y=LATE)) + 
  geom_line() +
  geom_ribbon(aes(ymin = CI_low, ymax = CI_high),alpha=0.2) +
  geom_point(x = 7.338641, y = 0.20016) +
  ggtitle("2014") +
  xlab("Bandwidth") +
  ylab("Treatment effect") +
  geom_hline(yintercept = 0, alpha = 0.5)
```
```{r grid plots all}
#make grid plots

all_dc_grid <- grid.arrange(grobs = list(dc_all_plot2$rdplot, dc_all_plot3$rdplot, dc_all_plot4$rdplot, dc_all_plot5$rdplot), ncol = 2, nrow = 2, top = "Rate of College Degrees for Mothers in Washington, DC")

all_dc_bw_grid <- grid.arrange(grobs = list(dc_all_bw2, dc_all_bw3, dc_all_bw4, dc_all_bw5), ncol = 2, nrow = 2, top = "Bandwidth Sensitivity Tests - Rates of College Degrees for Mothers in Washington, DC")
```


## Postgrad Degree

```{r DC 2 years postgrad}
#DC 2 years after implementation, postgrad

#create initial subset
dc2yrs <- subset(dcmoms, dcmoms$YEAR == 2011)

#create data table for regression
dc2yrs_reg <- rdd_data(y = dc2yrs$postgrad, x = dc2yrs$YNGCH, cutpoint = 7, covar = dc2yrs$AGE)

#find optimal bandwidth
bw_ik <- rdd_bw_ik(dc2yrs_reg)

#run regression based on optimal bandwidth
(reg_nonpara2 <- rdd_reg_np(rdd_object=dc2yrs_reg, bw=bw_ik))

#no subset adjustment needed because optimal bandwidth covers all observations
dc2yrs <- subset(dc2yrs, dc2yrs$YNGCH <= 16)

#plot regression discontinuity graph
dc_postgrad_plot2 <- rdplot(y = dc2yrs$postgrad, x = dc2yrs$YNGCH, c = 7, p = 1, col.dots = "black", col.lines = "black", title = "2011", x.label = "Age of Youngest Child", y.label = "% Postgraduate Degree")

#bandwidth sensitivity test
bw_test <- plotSensi(reg_nonpara2, from=2, to=18, by=1)
dc_postgrad_bw2 <- ggplot(bw_test, aes(x=bw, y=LATE)) + 
  geom_line() +
  geom_ribbon(aes(ymin = CI_low, ymax = CI_high),alpha=0.2) +
  geom_point(x = 6.744515, y = -0.17447) +
  ggtitle("2011") +
  xlab("Bandwidth") +
  ylab("Treatment effect") +
  geom_hline(yintercept = 0, alpha = 0.5)
```

```{r DC 3 years postgrad}
#DC 3 years after implementation, postgrad

#create initial subset
dc3yrs <- subset(dcmoms, dcmoms$YEAR == 2012)

#create data table for regression
dc3yrs_reg <- rdd_data(y = dc3yrs$postgrad, x = dc3yrs$YNGCH, cutpoint = 8)

#find optimal bandwidth
bw_ik <- rdd_bw_ik(dc3yrs_reg)

#run regression based on optimal bandwidth
(reg_nonpara3 <- rdd_reg_np(rdd_object=dc3yrs_reg, bw=bw_ik))

#no subset adjustment needed because optimal bandwidth covers all observations

#plot regression discontinuity graph
dc_postgrad_plot3 <- rdplot(y = dc3yrs$postgrad, x = dc3yrs$YNGCH, c = 8, p = 1, masspoints = "off", col.dots = "black", col.lines = "black", title = "2012", x.label = "Age of Youngest Child", y.label = "% Postgraduate Degree")

#bandwidth sensitivity test
bw_test <- plotSensi(reg_nonpara3, from=2, to=18, by=1)
dc_postgrad_bw3 <- ggplot(bw_test, aes(x=bw, y=LATE)) + 
  geom_line() +
  geom_ribbon(aes(ymin = CI_low, ymax = CI_high),alpha=0.2) +
  geom_point(x = 9.572123, y = -0.015219) +
  ggtitle("2012") +
  xlab("Bandwidth") +
  ylab("Treatment effect") +
  geom_hline(yintercept = 0, alpha = 0.5)
```

```{r DC 4 years postgrad}
#DC 4 years after implementation, postgrad

#create initial subset
dc4yrs <- subset(dcmoms, dcmoms$YEAR == 2013)

#create data table for regression
dc4yrs_reg <- rdd_data(y = dc4yrs$postgrad, x = dc4yrs$YNGCH, cutpoint = 9)

#find optimal bandwidth
bw_ik <- rdd_bw_ik(dc4yrs_reg)

#run regression based on optimal bandwidth
(reg_nonpara4 <- rdd_reg_np(rdd_object=dc4yrs_reg, bw=bw_ik))

#no subset adjustment needed because optimal bandwidth covers all observations

#plot regression discontinuity graph
dc_postgrad_plot4 <- rdplot(y = dc4yrs$postgrad, x = dc4yrs$YNGCH, c = 9, p = 1, masspoints = "off", col.dots = "black", col.lines = "black", title = "2013", x.label = "Age of Youngest Child", y.label = "% Postgraduate Degree")

#bandwidth sensitivity test
bw_test <- plotSensi(reg_nonpara4, from=2, to=18, by=1)
dc_postgrad_bw4 <- ggplot(bw_test, aes(x=bw, y=LATE)) + 
  geom_line() +
  geom_ribbon(aes(ymin = CI_low, ymax = CI_high),alpha=0.2) +
  geom_point(x = 6.514625, y = -0.17308) +
  ggtitle("2013") +
  xlab("Bandwidth") +
  ylab("Treatment effect") +
  geom_hline(yintercept = 0, alpha = 0.5)
```

```{r DC 5 years postgrad}
#DC 5 years after implementation, postgrad

#create initial subset
dc5yrs <- subset(dcmoms, dcmoms$YEAR == 2014)

#create data table for regression
dc5yrs_reg <- rdd_data(y = dc5yrs$postgrad, x = dc5yrs$YNGCH, cutpoint = 10)

#find optimal bandwidth
bw_ik <- rdd_bw_ik(dc5yrs_reg)

#run regression based on optimal bandwidth
(reg_nonpara5 <- rdd_reg_np(rdd_object=dc5yrs_reg, bw=bw_ik))

#no subset adjustment needed because optimal bandwidth covers all observations
dc5yrs <- subset(dc5yrs, dc5yrs$YNGCH >= 2 & dc5yrs$YNGCH <= 16)

#plot regression discontinuity graph
dc_postgrad_plot5 <- rdplot(y = dc5yrs$postgrad, x = dc5yrs$YNGCH, c = 10, p = 1, col.dots = "black", col.lines = "black", title = "2014", x.label = "Age of Youngest Child", y.label = "% Postgraduate Degree")

#bandwidth sensitivity test
bw_test <- plotSensi(reg_nonpara5, from=2, to=18, by=1)
dc_postgrad_bw5 <- ggplot(bw_test, aes(x=bw, y=LATE)) + 
  geom_line() +
  geom_ribbon(aes(ymin = CI_low, ymax = CI_high),alpha=0.2) +
  geom_point(x = 7.874217, y = 0.097313) +
  ggtitle("2014") +
  xlab("Bandwidth") +
  ylab("Treatment effect") +
  geom_hline(yintercept = 0, alpha = 0.5)
```
```{r grid plots postgrad}
#make grid plots

postgrad_dc_grid <- grid.arrange(grobs = list(dc_postgrad_plot2$rdplot, dc_postgrad_plot3$rdplot, dc_postgrad_plot4$rdplot, dc_postgrad_plot5$rdplot), ncol = 2, nrow = 2, top = "Rate of Postgraduate Degrees for Mothers in Washington, DC")

postgrad_dc_bw_grid <- grid.arrange(grobs = list(dc_postgrad_bw2, dc_postgrad_bw3, dc_postgrad_bw4, dc_postgrad_bw5), ncol = 2, nrow = 2, top = "Bandwidth Sensitivity Tests - Rates of Postgraduate Degrees for Mothers in Washington, DC")
```