---
title: "Florida Summary Stats"
output: html_notebook
---

Note! Run this after you've already run Analysis so all the data is loaded.

```{r}
#Florida in 2005

#separate all moms in 2005 into subset
Flin2005 <- subset(floridamoms, floridamoms$YEAR == 2005)

#percent married
marriedfl05 <- (length(which(Flin2005$MARST == 1))/length(Flin2005$MARST)) *100
print(marriedfl05)

#percent immigrant (defined as born outside the US)
immigrantfl05 <- (length(which(Flin2005$BPL >= 100))/length(Flin2005$BPL)) *100
print(immigrantfl05)

#race
racefl05 <- Flin2005 %>% group_by(Flin2005$RACE) %>% summarise(Percentage=n()/nrow(.))
racefl05


#household income, age, education
sumstats2005fl <- select(Flin2005, HHINCOME, AGE, MYEDUC)
summary(sumstats2005fl)
```

```{r}
#Florida in 2010

#seperate all moms in 2010 into subset
Flin2010 <- subset(floridamoms, floridamoms$YEAR == 2010)

#percent married
marriedfl10 <- (length(which(Flin2010$MARST == 1))/length(Flin2010$MARST)) *100
print(marriedfl10)

#percent immigrant (defined as born outside the US)
immigrantfl10 <- (length(which(Flin2010$BPL >= 100))/length(Flin2010$BPL)) *100
print(immigrantfl10)

#race
racefl10 <- Flin2010 %>% group_by(Flin2010$RACE) %>% summarise(Percentage=n()/nrow(.))
racefl10


#household income, age, education
sumstats2010fl <- select(Flin2010, HHINCOME, AGE, MYEDUC)
summary(sumstats2010fl)
```

```{r}
#Florida in 2015

#separate all moms in 2010 into subset
Flin2015 <- subset(floridamoms, floridamoms$YEAR == 2015)

#percent married
marriedfl15 <- (length(which(Flin2015$MARST == 1))/length(Flin2015$MARST)) *100
print(marriedfl15)

#percent immigrant (defined as born outside the US)
immigrantfl15 <- (length(which(Flin2015$BPL >= 100))/length(Flin2015$BPL)) *100
print(immigrantfl15)

#race
racefl15 <- Flin2015 %>% group_by(Flin2015$RACE) %>% summarise(Percentage=n()/nrow(.))
racefl15


#household income, age, education
sumstats2015fl <- select(Flin2015, HHINCOME, AGE, MYEDUC)
summary(sumstats2015fl)
```

```{r}
#Georgia in 2005

georgiamoms <- subset(moms, moms$STATEICP == 44)

#separate all moms in 2005 into subset
Gain2005 <- subset(georgiamoms, georgiamoms$YEAR == 2005)

#percent married
marriedga05 <- (length(which(Gain2005$MARST == 1))/length(Gain2005$MARST)) *100
print(marriedga05)

#percent immigrant (defined as born outside the US)
immigrantga05 <- (length(which(Gain2005$BPL >= 100))/length(Gain2005$BPL)) *100
print(immigrantga05)

#race
racega05 <- Gain2005 %>% group_by(Gain2005$RACE) %>% summarise(Percentage=n()/nrow(.))
racega05


#household income, age, education
sumstats2005ga <- select(Gain2005, HHINCOME, AGE, MYEDUC)
summary(sumstats2005ga)
```

```{r}
#Georgia in 2010

#separate all moms in 2010 into subset
Gain2010 <- subset(georgiamoms, georgiamoms$YEAR == 2010)

#percent married
marriedga10 <- (length(which(Gain2010$MARST == 1))/length(Gain2010$MARST)) *100
print(marriedga10)

#percent immigrant (defined as born outside the US)
immigrantga10 <- (length(which(Gain2010$BPL >= 100))/length(Gain2010$BPL)) *100
print(immigrantga10)

#race
racega10 <- Gain2010 %>% group_by(Gain2010$RACE) %>% summarise(Percentage=n()/nrow(.))
racega10


#household income, age, education
sumstats2010ga <- select(Gain2010, HHINCOME, AGE, MYEDUC)
summary(sumstats2010ga)
```


```{r}
#Georgia (PUMAs) in 2005

#separate all moms in 2005 into subset
Gain2005_puma <- subset(pumaga, pumaga$YEAR == 2005)

#percent married
marriedga05_puma <- (length(which(Gain2005_puma$MARST == 1))/length(Gain2005_puma$MARST)) *100
print(marriedga05_puma)

#percent immigrant (defined as born outside the US)
immigrantga05_puma <- (length(which(Gain2005_puma$BPL >= 100))/length(Gain2005_puma$BPL)) *100
print(immigrantga05_puma)

#race
racega05_puma <- Gain2005_puma %>% group_by(Gain2005_puma$RACE) %>% summarise(Percentage=n()/nrow(.))
racega05_puma


#household income, age, education
sumstats2005ga_puma <- select(Gain2005_puma, HHINCOME, AGE, MYEDUC)
summary(sumstats2005ga_puma)
```

```{r}
#Georgia (PUMAs) in 2010

#separate all moms in 2010 into subset
Gain2010_puma <- subset(pumaga, pumaga$YEAR == 2010)

#percent married
marriedga09_puma <- (length(which(Gain2010_puma$MARST == 1))/length(Gain2010_puma$MARST)) *100
print(marriedga09_puma)

#percent immigrant (defined as born outside the US)
immigrantga09_puma <- (length(which(Gain2010_puma$BPL >= 100))/length(Gain2010_puma$BPL)) *100
print(immigrantga09_puma)

#race
racega09_puma <- Gain2010_puma %>% group_by(Gain2010_puma$RACE) %>% summarise(Percentage=n()/nrow(.))
racega09_puma


#household income, age, education
sumstats2009ga_puma <- select(Gain2010_puma, HHINCOME, AGE, MYEDUC)
summary(sumstats2009ga_puma)
```

